<script>
	import { Button } from '$lib/ui/button/index.js';
	import { ArrowRight } from 'lucide-svelte';
	import { page } from '$app/stores';
	import { goto } from '$app/navigation';

	export let onAuthRequest = () => {};

	function handleCtaClick() {
		if ($page.data.session) {
			const username = $page.data.session.user?.user_metadata?.username;
			goto(username ? `/${username}` : '/profile');
		} else {
			onAuthRequest();
		}
	}
</script>

<div class="container mx-auto max-w-5xl px-6">
	<section class="my-8 rounded-2xl overflow-hidden shadow-lg bg-white">
		<div
			class="bg-gradient-to-br from-yellow-50 via-amber-50 to-orange-50 px-8 py-14 text-center md:px-12 md:py-20"
		>
			<div class="mx-auto max-w-3xl space-y-6">
				<p class="text-lg font-medium tracking-widest uppercase text-stone-600">
					For Human Creators
				</p>
				<h1 class="text-4xl font-bold tracking-tight text-balance text-zinc-900 md:text-6xl">
					Made by people, not prompts
				</h1>
				<p class="text-lg leading-8 text-zinc-600 text-balance md:text-xl">
					Your followers can't tell if your work is real
				</p>
				<p class="mx-auto max-w-2xl text-base leading-7 text-zinc-500 md:text-lg">
					Proof in Bio is a verified gallery that proves your photos were captured by a human with a
					real camera, not generated by AI. Built on the same standard trusted by Adobe, Google,
					Sony, and the BBC.
				</p>
				<div class="flex flex-col items-center gap-4 pt-2">
					<Button size="lg" class="group text-white font-bold" onclick={handleCtaClick}>
						Create Your Verified Gallery
						<ArrowRight class="ml-2 h-5 w-5 transition-transform group-hover:translate-x-1" />
					</Button>
					<p class="text-sm font-medium text-stone-600">
						No credit card required &middot; 50 photos free &middot; 2-minute setup
					</p>
				</div>
			</div>
		</div>
	</section>
</div>
