<script>
    import { Fingerprint } from 'lucide-svelte';
</script>

<div class="rounded-xl border border-green-600/20 dark:border-green-500/20 bg-white dark:bg-gray-950/50 p-4 mb-6 relative overflow-hidden shadow-sm dark:shadow-none backdrop-blur-sm">
    <div class="flex items-center gap-4 relative z-10">
        <div class="relative flex-shrink-0">
            <div class="absolute inset-0 bg-green-400/20 dark:bg-green-500/30 blur-2xl rounded-full scale-150"></div>
            <Fingerprint class="w-12 h-12 text-green-600 dark:text-green-400 relative" strokeWidth={1} />
        </div>
        
        <div class="flex-1 text-left">
            <h2 class="text-lg font-semibold dark:text-white mb-1">
                <span class="text-green-700 dark:text-green-400">C2PA Verified</span>
            </h2>
            <p class="text-gray-600 dark:text-gray-400 text-sm leading-relaxed">
                This means that this image has not been generated by AI, or over edited. 
                <span class="text-gray-900 dark:text-gray-200 font-medium">Human created content only.</span>
            </p>
        </div>
    </div>
</div>